/*
 * This file is generated by jOOQ.
 */
package com.nguyenanhtuyen.testjooq;


import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_CATALOG</code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    /**
     * The schema <code>testjooq</code>.
     */
    public final Testjooq TESTJOOQ = Testjooq.TESTJOOQ;

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }

   /* @Override
    public final List<Schema> getSchemas() {
        return Arrays.asList(
            Testjooq.TESTJOOQ
        );
    }*/
}
