/*
 * This file is generated by jOOQ.
 */
package com.nguyenanhtuyen.testjooq;


import com.nguyenanhtuyen.testjooq.tables.Class;
import com.nguyenanhtuyen.testjooq.tables.Student;
import com.nguyenanhtuyen.testjooq.tables.records.ClassRecord;
import com.nguyenanhtuyen.testjooq.tables.records.StudentRecord;

import javax.annotation.processing.Generated;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * testjooq.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ClassRecord> KEY_CLASS_PRIMARY = Internal.createUniqueKey(Class.CLASS, DSL.name("KEY_class_PRIMARY"), new TableField[] { Class.CLASS.ID }, true);
    public static final UniqueKey<StudentRecord> KEY_STUDENT_PRIMARY = Internal.createUniqueKey(Student.STUDENT, DSL.name("KEY_student_PRIMARY"), new TableField[] { Student.STUDENT.ID }, true);
}
