/*
 * This file is generated by jOOQ.
 */
package com.nguyenanhtuyen.testjooq;


import com.nguyenanhtuyen.testjooq.tables.Class;
import com.nguyenanhtuyen.testjooq.tables.Student;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in testjooq.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>testjooq.class</code>.
     */
    public static final Class CLASS = Class.CLASS;

    /**
     * The table <code>testjooq.student</code>.
     */
    public static final Student STUDENT = Student.STUDENT;
}
