/*
 * This file is generated by jOOQ.
 */
package com.nguyenanhtuyen.testjooq;


import com.nguyenanhtuyen.testjooq.tables.Class;
import com.nguyenanhtuyen.testjooq.tables.Student;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Testjooq extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>testjooq</code>
     */
    public static final Testjooq TESTJOOQ = new Testjooq();

    /**
     * The table <code>testjooq.class</code>.
     */
    public final Class CLASS = Class.CLASS;

    /**
     * The table <code>testjooq.student</code>.
     */
    public final Student STUDENT = Student.STUDENT;

    /**
     * No further instances allowed
     */
    private Testjooq() {
        super("testjooq", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

   /* @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Class.CLASS,
            Student.STUDENT
        );
    }*/
}
